### ISSUE TITLE
Error in line 263.

### ISSUE THREAD

**Issue by Wodki** [devsnek/snekfetch#11]
So I am using the discordjs lib quite long time and have never had this issue before so it perhaps has something to do with the recent update.

I am getting this error (I'll include where it comes from discordjs)

    at item.request.gen.end (../node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:69:74)
    at then (../node_modules/snekfetch/src/index.js:263:21)
    at process._tickDomainCallback (internal/process/next_tick.js:129:7)

I had never had this issue before but as of two days ago it has happened four times at competely random intervals.

**Comment by devsnek** [comment]
https://github.com/hydrabolt/discord.js
