### ISSUE TITLE
Unexpected token

### ISSUE THREAD

**Issue by jj2neat** [devsnek/snekfetch#39]
## Version or commit hash:

snekfetch@4.0.0

## Explanation of issue:

Whenever I require snekfetch (windows 10 laptop)

## Example code to reproduce:
```js
C:\Users\User\node_modules\snekfetch\src\index.js:202
    );
    ^
SyntaxError: Unexpected token )
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)

```

- [ ] Issue occurs in browser
- [x] Issue occurs in node

**Comment by devsnek** [comment]
what version of node are you using

**Comment by jj2neat** [comment]
6.11 i just realized how old this laptops node is.. will be updating to v10
